// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVn4r7iO9j0-Dv5cWqnVcKewIsog4X0_Q',
    appId: '1:212513626815:web:edfb94990a5459ee4e440a',
    messagingSenderId: '212513626815',
    projectId: 'testingproject-f20cb',
    authDomain: 'testingproject-f20cb.firebaseapp.com',
    storageBucket: 'testingproject-f20cb.appspot.com',
    measurementId: 'G-LG01K9FYKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPcpUa0Pp58z0FkPCNxH6jAykHgoBtqUw',
    appId: '1:212513626815:android:58f1771ef0f86b004e440a',
    messagingSenderId: '212513626815',
    projectId: 'testingproject-f20cb',
    storageBucket: 'testingproject-f20cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3nnKynJU14IO5hteaBH4sMj8RjvZLfB8',
    appId: '1:212513626815:ios:91fac98a28644c654e440a',
    messagingSenderId: '212513626815',
    projectId: 'testingproject-f20cb',
    storageBucket: 'testingproject-f20cb.appspot.com',
    iosClientId: '212513626815-q816796s8nd40612kavv4mev6mffb8qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3nnKynJU14IO5hteaBH4sMj8RjvZLfB8',
    appId: '1:212513626815:ios:91fac98a28644c654e440a',
    messagingSenderId: '212513626815',
    projectId: 'testingproject-f20cb',
    storageBucket: 'testingproject-f20cb.appspot.com',
    iosClientId: '212513626815-q816796s8nd40612kavv4mev6mffb8qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationFcm',
  );
}
