name: notification_module
description: A repository for the Notifications domain.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_messaging: ^14.6.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
